server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #标识定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json,文本则设置"text/plain"
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: atguiguA #增加分组看以避免重复消费,也可以避免消息丢失
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2    #设置心跳的时间间隔(默认30秒)
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔(默认90秒)
    instance-id: receive-8802.com  #在信息列表时显示主机名称
    prefer-ip-address: true #访问的路径变成IP地址