# =========================
#       路由写死的方式
# =========================
#server:
#  port: 9527
#spring:
#  application:
#    name: cloud-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: payment_routh #payment_route 路由的ID 没有固定规则但要求唯一,建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/**  #断言,路径相匹配的进行路由
#
#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**



# =========================
#       动态路由方式
# =========================
server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启注册中心路由功能,利用微服务名进行路由
      #          lower-case-service-id: true
      routes:
        - id: payment_routh
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址;
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka #单机
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群


